[keyboard]
bindings = [
    { key = "Equals", mods = "Command", action = "DecreaseFontSize" },
    { key = "Slash", mods = "Command", action = "IncreaseFontSize" },
    { key = "T", mods = "Command", chars = "\u0001c" },
    { key = "W", mods = "Command", chars = "\u0001d" },

    { key = "LBracket", mods = "Command|Shift", chars = "\u0001p" },
    { key = "RBracket", mods = "Command|Shift", chars = "\u0001n" },
    { key = "Left", mods = "Alt", chars = "\u001Bb" },
    { key = "Right", mods = "Alt", chars = "\u001Bf" },

    { key = "Key1", mods = "Command", chars = "\u00141" },
    { key = "Key2", mods = "Command", chars = "\u00142" },
    { key = "Key3", mods = "Command", chars = "\u00143" },
    { key = "Key4", mods = "Command", chars = "\u00144" },
    { key = "Key5", mods = "Command", chars = "\u00145" },
    { key = "Key6", mods = "Command", chars = "\u00146" },
    { key = "Key7", mods = "Command", chars = "\u00147" },
    { key = "Key8", mods = "Command", chars = "\u00148" },
    { key = "Key9", mods = "Command", chars = "\u00149" },

    { key = "W", mods = "Command", chars = "\u0014&" },

    { key = "Up", mods = "Command", chars = "\u001B[1;3A" },
    { key = "Down", mods = "Command", chars = "\u001B[1;3B" },
    { key = "Left", mods = "Command", chars = "\u001B[1;3D" },
    { key = "Right", mods = "Command", chars = "\u001B[1;3C" },

    { key = "H", mods = "Alt", chars = "\u001BB" },
    { key = "L", mods = "Alt", chars = "\u001BF" },
]
