[keyboard]
bindings = [
    { key = "Return", mods = "Super", action = "ToggleFullScreen" },
    { key = "N", mods = "Super", action = "SpawnNewInstance" },

    { key = "C", mods = "Super", action = "Copy" },
    { key = "V", mods = "Super", action = "Paste" },
    { key = "H", mods = "Super", action = "Hide" },
    { key = "H", mods = "Super", action = "Quit" },

    { key = "Key0", mods = "Super", action = "ResetFontSize" },
    { key = "Equals", mods = "Super|Shift", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Super", action = "DecreaseFontSize" },
]
