tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/versions"
tap "caskroom/cask"

# Development
brew "git"
brew "node"
brew "python@2"
brew "python3"
brew "ipython"
brew "yarn"

# Shell software and eanager
brew "zsh"

# CLI utils
brew "rclone"
brew "tree"
brew "colordiff"

# Web browsers
cask "firefox"

# Media players
cask "iina"
cask "spotify"

# Misc.
cask "selfcontrol"
